spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect


